[build]
  publish = "dist"
  command = "npm install && npm run build:prod"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "9.8.1"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions]
  directory = "functions"

[functions.ai-generator]
  timeout = 30

[functions.email-capture]
  timeout = 10

[functions.blueprint-download]
  timeout = 15

[context.development]
  command = "npm install && npm run build:dev"

[context.development.environment]
  NODE_ENV = "development"
  DEBUG = "true"

[context.production]
  command = "npm install && npm run build:prod"

[context.production.environment]
  NODE_ENV = "production"
  DEBUG = "false"

[context.deploy-preview]
  command = "npm install && npm run build:preview"

[context.branch-deploy]
  command = "npm install && npm run build:branch"
